services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: yourUser
      POSTGRES_DB: yourDB
      POSTGRES_PASSWORD: yourPassword
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
