import { PrismaClient } from "@prisma/client";

export async function createAlunos(prisma: PrismaClient) {
  // Crie responsáveis primeiro
  const responsaveisData = [
    {
<<<<<<< HEAD
      nome: "Priscila de Santana",
      email: "pspibio@gmail.com",
      cpf: "791.064.555-49",
      telefone: "71999157057",
      endereco: {
        rua: "Rua Poetisa Cora Coralina",
        numero: "45",
        bairro: "Luis Anselmo",
        cidade: "Salvador",
        estado: "Bahia",
        cep: "40.261-075",
        complemento: "Ed. Félix, Apt. 01",
        referencia: "Próximo à Escola Estadual Santa Rita",
      },
      password: "$2a$12$8mEzsG7hKhYKuNgs0RW4fOK6AQREgPRkCEJtQmD5t.8nLGfPF6k0S",
    },
    {
      nome: "Adenilson Augusto Leal Junior",
      email: "aniel2@gmail.com",
      cpf: "776.599.705-00",
      telefone: "71991773362",
      endereco: {
        rua: "Rua das pitangueiras",
        numero: "20",
        bairro: "Matatu de Brotas",
        cidade: "Salvador",
        estado: "Bahia",
        cep: "40255-436",
        complemento: "Complemento Exemplo",
        referencia: "Ao lado da rádio piatã FM",
      },
      password: "$2a$12$8mEzsG7hKhYKuNgs0RW4fOK6AQREgPRkCEJtQmD5t.8nLGfPF6k0S",
    },
    {
      nome: "Cláudia Bispo",
      email: "",
      cpf: "",
      telefone: "7192994794",
      endereco: {
        rua: "Tv. Albertino Cabral Henrique",
        numero: "212",
        bairro: "Pituaçu",
        cidade: "Salvador",
        estado: "Bahia",
        cep: "41741-170",
        complemento: "Condomínio Parque Tropical, torre Sol, aptº 101",
=======
      nome: "Laís Sônia Rezende",
      email: "laissoniarezende@vuyu.es",
      cpf: "94641339457",
      telefone: "66999629620",
      endereco: {
        rua: "Avenida das Acácias",
        numero: "546",
        bairro: "Setor Residencial Sul",
        cidade: "Sinop",
        estado: "MT",
        cep: "78550059",
        complemento: "Complemento Ficticio",
>>>>>>> 2faddd0c6426d1e13ee4f3257978b897bb487c60
        referencia: "Referencia Ficticia",
      },
      password: "$2a$12$8mEzsG7hKhYKuNgs0RW4fOK6AQREgPRkCEJtQmD5t.8nLGfPF6k0S",
    },
    {
<<<<<<< HEAD
      nome: "Amanda Lima",
      email: "Amandasabrina_@hotmail.com",
      cpf: "80428827500",
      telefone: "71988032139",
      endereco: {
        rua: "Rua Amazonas",
        numero: "78",
        bairro: "Cabula",
        cidade: "Salvador",
        estado: "Bahia",
        cep: "41192-065",
        complemento: "Vila Arboreto torre 2 AP 801 ",
        referencia: "Na rua do posto",
      },
      password: "$2a$12$8mEzsG7hKhYKuNgs0RW4fOK6AQREgPRkCEJtQmD5t.8nLGfPF6k0S",
    },
    {
      nome: "Aurimar Dantas Alves Silva",
      email: "",
      cpf: "",
      telefone: "71996562601",
      endereco: {
        rua: "Av Santos Dumont",
        numero: "1893",
        bairro: "Centro",
        cidade: "Lauro de Freitas",
        estado: "Bahia",
        cep: "42702-400",
        complemento: "Ap 904 - Ed Bella - Cond Supremo Family",
        referencia: "Em frente ao Hospital Aeroporto",
      },
      password: "$2a$12$8mEzsG7hKhYKuNgs0RW4fOK6AQREgPRkCEJtQmD5t.8nLGfPF6k0S",
    },
    {
      nome: "Aline Oliveira Ribeiro de Azevedo",
      email: "alineribeiro.social@gmail.com",
      cpf: "83235736549",
      telefone: "71991988959",
      endereco: {
        rua: "Rua da Gratidão",
        numero: "",
        bairro: "Piatã",
        cidade: "Salvador",
        estado: "Bahia",
        cep: "41650195",
        complemento: "Condomínio colinas de piata, edifício turmalina, aptm 805",
        referencia: "",
      },
      password: "$2a$12$8mEzsG7hKhYKuNgs0RW4fOK6AQREgPRkCEJtQmD5t.8nLGfPF6k0S",
    },
    {
      nome: "Sued Lorena Lima Batista",
      email: "",
      cpf: "04084168580",
      telefone: "71999002728",
      endereco: {
        rua: "Avenida São Roque",
        numero: "364",
        bairro: "Uruguai",
        cidade: "Salvador",
        estado: "Bahia",
        cep: "40450355",
        complemento: "Condomínio colinas de piata, edifício turmalina, aptm 805",
        referencia: "Em cima da Creche de Nilda",
      },
      password: "$2a$12$8mEzsG7hKhYKuNgs0RW4fOK6AQREgPRkCEJtQmD5t.8nLGfPF6k0S",
    },
    {
      nome: "Daniela Oliveira",
      email: "",
      cpf: "",
      telefone: "71981010886 ",
      endereco: {
        rua: "Rua Embira",
        numero: "149",
        bairro: "Patamares",
        cidade: "Salvador",
        estado: "Bahia",
        cep: "41680-113",
        complemento: "",
        referencia: "Greenville ",
      },
      password: "$2a$12$8mEzsG7hKhYKuNgs0RW4fOK6AQREgPRkCEJtQmD5t.8nLGfPF6k0S",
    },
    {
      nome: "Daniela Oliveira",
      email: "",
      cpf: "",
      telefone: "71981010886 ",
      endereco: {
        rua: "Rua Embira",
        numero: "149",
        bairro: "Patamares",
        cidade: "Salvador",
        estado: "Bahia",
        cep: "41680-113",
        complemento: "",
        referencia: "Greenville ",
      },
      password: "$2a$12$8mEzsG7hKhYKuNgs0RW4fOK6AQREgPRkCEJtQmD5t.8nLGfPF6k0S",
    },
    {
      nome: "Magda Carvalo",
      email: "",
      cpf: "87926768553",
      telefone: "7191841308",
      endereco: {
        rua: "Rua hilton Rodrigues",
        numero: "158",
        bairro: "Pituba",
        cidade: "Salvador",
        estado: "Bahia",
        cep: "41830630",
        complemento: "apt 702 edf portal do bosque ",
        referencia: "Próximo ao hiper ideal",
      },
      password: "$2a$12$8mEzsG7hKhYKuNgs0RW4fOK6AQREgPRkCEJtQmD5t.8nLGfPF6k0S",
    },
    {
      nome: "Marinalva Guedes",
      email: "adv.marinalvaguedes@hotmail.com",
      cpf: "0804240582",
      telefone: "71999255964",
      endereco: {
        rua: "Rua Rio de São Pedro",
        numero: "16",
        bairro: "Graça",
        cidade: "Salvador",
        estado: "Bahia",
        cep: "40150350",
        complemento: "Ed. Mansão Rio de São Pedro",
        referencia: "Próximo à clínica oftalmológica Leitão  Guerra",
      },
      password: "$2a$12$8mEzsG7hKhYKuNgs0RW4fOK6AQREgPRkCEJtQmD5t.8nLGfPF6k0S",
    },
    {
      nome: "Sâmia Cheade",
      email: "",
      cpf: "",
      telefone: "71999665277",
      endereco: {
        rua: "Rua Hilton Rodrigues",
        numero: "71",
        bairro: "Pituba",
        cidade: "Salvador",
        estado: "Bahia",
        cep: "41830630",
        complemento: "aptº 1103, Edf Torremolinos",
        referencia: "Final da rua Ceará, após o Hiper Ideal",
      },
      password: "$2a$12$8mEzsG7hKhYKuNgs0RW4fOK6AQREgPRkCEJtQmD5t.8nLGfPF6k0S",
    },
    {
      nome: "Solimar Costa",
      email: "",
      cpf: "",
      telefone: "71996527437",
      endereco: {
        rua: "Rua Maranhão",
        numero: "373",
        bairro: "Pituba",
        cidade: "Salvador",
        estado: "Bahia",
        cep: "41830260",
        complemento: "Edf Mansão Vela Branca, apto 901",
        referencia: "Próximo Hotel Manhatan",
=======
      nome: "Raul Ricardo Breno Farias",
      email: "raul-farias70@netwis.com.br",
      cpf: "53501568029",
      telefone: "27987441439",
      endereco: {
        rua: "Rua Ivo Beltrame",
        numero: "379",
        bairro: "Boa Vista",
        cidade: "São Mateus",
        estado: "ES",
        cep: "29931270",
        complemento: "Complemento Exemplo",
        referencia: "Referencia Exemplo",
>>>>>>> 2faddd0c6426d1e13ee4f3257978b897bb487c60
      },
      password: "$2a$12$8mEzsG7hKhYKuNgs0RW4fOK6AQREgPRkCEJtQmD5t.8nLGfPF6k0S",
    },
  ];

  // Crie responsáveis
  const responsaveis = await prisma.responsavel.createMany({
    data: responsaveisData,
    skipDuplicates: true,
  });

  // Busque os IDs dos responsáveis criados
  const responsaveisIds = await prisma.responsavel.findMany({
    where: {
      email: { in: responsaveisData.map((r) => r.email) },
    },
    select: { id: true, email: true },
  });

  // Mapeie os responsáveis pelo email para facilitar a associação
  const responsavelMap = Object.fromEntries(responsaveisIds.map((r) => [r.email, r.id]));

  // Dados dos alunos
  const alunosData = [
    {
<<<<<<< HEAD
      nome: "Adam de Santana Soares Pinto Pereira",
      email: "adampereira1@gmail.com",
      escola: "Salesiano do Salvador",
      ano_escolar: "6º Ano",
      telefone: "71999157057",
      endereco: {
        rua: "Rua Poetisa Cora Coralina",
        numero: "45",
        bairro: "Luis Anselmo",
        cidade: "Salvador",
        estado: "Bahia",
        cep: "40.261-075",
        complemento: "Ed. Félix, Apt. 01",
        referencia: "Próximo à Escola Estadual Santa Rita",
=======
      nome: "Mirella Esther Rodrigues",
      email: "mirella-rodrigues94@gmailo.com",
      escola: "Escola Mundo e Criação",
      ano_escolar: "1º Ano",
      telefone: "44986975139",
      endereco: {
        rua: "Avenida Prefeito Antônio Teodoro de Oliveira",
        numero: "631",
        bairro: "Jardim Santa Cruz",
        cidade: "Campo Mourão",
        estado: "PR",
        cep: "87309596",
        complemento: "Complemento Ficticio",
        referencia: "Referencia Ficticia",
>>>>>>> 2faddd0c6426d1e13ee4f3257978b897bb487c60
      },
      password: "$2a$12$8mEzsG7hKhYKuNgs0RW4fOK6AQREgPRkCEJtQmD5t.8nLGfPF6k0S",
      ficha: "Ficha Ficticia",
      modalidade: {
        presencial: true,
        online: false,
      },
<<<<<<< HEAD
      qtd_aulas: 8,
      data_inicio: new Date(),
      responsavelId: responsavelMap["adampereira1@gmail.com"],
=======
      responsavelId: responsavelMap["raul-farias70@netwis.com.br"],
>>>>>>> 2faddd0c6426d1e13ee4f3257978b897bb487c60
      ativo: true,
      financeiro: {
        qtd_aulas: 7,
        valor: "445",
        dta_vencimento: "10/12",
      },
    },
    {
<<<<<<< HEAD
      nome: "Adenilson Augusto Leal Neto",
      email: "",
      escola: "Mediterrâneo",
      ano_escolar: "9º Ano",
      telefone: "71991773362",
      endereco: {
        rua: "Rua das pitangueiras",
        numero: "20",
        bairro: "Matatu de Brotas",
        cidade: "Salvador",
        estado: "Bahia",
        cep: "40255-436",
        complemento: "",
        referencia: "Ao lado da rádio piatã FM",
      },
      password: "$2a$12$8mEzsG7hKhYKuNgs0RW4fOK6AQREgPRkCEJtQmD5t.8nLGfPF6k0S",
      ficha: "Ficha Exemplo",
      modalidade: {
        presencial: false,
        online: true,
      },
      qtd_aulas: 8,
      data_inicio: new Date(),
      responsavelId: responsavelMap["aniel2@gmail.com"],
      ativo: true,
    },
    {
      nome: "Aila Vitória Bispo Araujo",
      email: "",
      escola: "",
      ano_escolar: "3º Ano do Ensino Médio",
      telefone: "7192994794",
      endereco: {
        rua: "Tv. Albertino Cabral Henrique",
        numero: "212",
        bairro: "Pituaçu",
        cidade: "Salvador",
        estado: "Bahia",
        cep: "41741-170",
        complemento: "Condomínio Parque Tropical, torre Sol, aptº 101",
        referencia: "",
=======
      nome: "Tomás Kaique Lima",
      email: "tomas_lima@live.co.uk",
      escola: "Marista",
      ano_escolar: "2º Ano",
      telefone: "71999157059",
      endereco: {
        rua: "Rua Otacílio Colaço da Costa",
        numero: "610",
        bairro: "Monte Santo",
        cidade: "Campina Grande",
        estado: "PB",
        cep: "58400815",
        complemento: "Complemento Exemplo",
        referencia: "Referencia Exemplo",
>>>>>>> 2faddd0c6426d1e13ee4f3257978b897bb487c60
      },
      password: "$2a$12$8mEzsG7hKhYKuNgs0RW4fOK6AQREgPRkCEJtQmD5t.8nLGfPF6k0S",
      ficha: "Ficha Exemplo",
      modalidade: {
        presencial: true,
        online: false,
      },
<<<<<<< HEAD
      qtd_aulas: 8,
      data_inicio: new Date(),
      responsavelId: responsavelMap[""],
      ativo: true,
    },
    {
      nome: "Alice Lima de Magalhães",
      email: "",
      escola: "Vitória Regia",
      ano_escolar: "2º Ano",
      telefone: "71988032139",
      endereco: {
        rua: "Rua Amazonas",
        numero: "78",
        bairro: "Cabula",
        cidade: "Salvador",
        estado: "Bahia",
        cep: "41192065",
        complemento: "Vila Arboreto torre 2 AP 801",
        referencia: "Na rua do posto",
      },
      password: "$2a$12$8mEzsG7hKhYKuNgs0RW4fOK6AQREgPRkCEJtQmD5t.8nLGfPF6k0S",
      ficha: "Ficha Exemplo",
      modalidade: {
        presencial: true,
        online: false,
      },
      qtd_aulas: 8,
      data_inicio: new Date(),
      responsavelId: responsavelMap["Amandasabrina_@hotmail.com"],
      ativo: true,
    },
    {
      nome: "Amanda Dantas Alves Silva",
      email: "",
      escola: "Colegio Apoio - Vilas",
      ano_escolar: "1º Ano do Ensino Médio",
      telefone: "71988032139",
      endereco: {
        rua: "Av Santos Dumont",
        numero: "1893",
        bairro: "Centro",
        cidade: "Lauro de Freitas",
        estado: "Bahia",
        cep: "42702400",
        complemento: "Ap 904 - Ed Bella - Cond Supremo Family",
        referencia: "Em frente ao Hospital Aeroporto",
      },
      password: "$2a$12$8mEzsG7hKhYKuNgs0RW4fOK6AQREgPRkCEJtQmD5t.8nLGfPF6k0S",
      ficha: "Ficha Exemplo",
      modalidade: {
        presencial: false,
        online: true,
      },
      qtd_aulas: 8,
      data_inicio: new Date(),
      responsavelId: responsavelMap[""],
      ativo: true,
    },
    {
      nome: "Ana Beatriz Ribeiro De Azevedo",
      email: "",
      escola: "Salesino Dom Bosco",
      ano_escolar: "2º Ano do Ensino Médio",
      telefone: "71991988959",
      endereco: {
        rua: "Rua da Gratidão",
        numero: "",
        bairro: "Piatã",
        cidade: "Salvador",
        estado: "Bahia",
        cep: "41650195",
        complemento: "Condomínio Colinas de Piatã, Edifício Turmalina, Apt 805",
        referencia: "",
      },
      password: "$2a$12$8mEzsG7hKhYKuNgs0RW4fOK6AQREgPRkCEJtQmD5t.8nLGfPF6k0S",
      ficha: "Ficha Exemplo",
      modalidade: {
        presencial: true,
        online: false,
      },
      qtd_aulas: 8,
      data_inicio: new Date(),
      responsavelId: responsavelMap["alineribeiro.social@gmail.com"],
      ativo: true,
    },
    {
      nome: "Ana Clara Lima Batista",
      email: "",
      escola: "Colégio Análise",
      ano_escolar: "2º Ano do Ensino Médio",
      telefone: "71999002728",
      endereco: {
        rua: "Avenida São Roque",
        numero: "364",
        bairro: "Uruguai",
        cidade: "Salvador",
        estado: "Bahia",
        cep: "40450-355",
        complemento: "",
        referencia: "Em cima da Creche de Nilda",
      },
      password: "$2a$12$8mEzsG7hKhYKuNgs0RW4fOK6AQREgPRkCEJtQmD5t.8nLGfPF6k0S",
      ficha: "Ficha Exemplo",
      modalidade: {
        presencial: false,
        online: true,
      },
      qtd_aulas: 12,
      data_inicio: new Date(),
      responsavelId: responsavelMap[""],
      ativo: true,
    },
    {
      nome: "Ana Luisa Oliveira Pereira",
      email: "",
      escola: "Sartre",
      ano_escolar: "4º Ano",
      telefone: "71981010886",
      endereco: {
        rua: "Rua Embira",
        numero: "149",
        bairro: "Patamares",
        cidade: "Salvador",
        estado: "Bahia",
        cep: "41680-113",
        complemento: "",
        referencia: "Greenville ",
      },
      password: "$2a$12$8mEzsG7hKhYKuNgs0RW4fOK6AQREgPRkCEJtQmD5t.8nLGfPF6k0S",
      ficha: "Ficha Exemplo",
      modalidade: {
        presencial: true,
        online: false,
      },
      qtd_aulas: 4,
      data_inicio: new Date(),
      responsavelId: responsavelMap[""],
      ativo: true,
    },
    {
      nome: "Ana Luiza Leão",
      email: "",
      escola: "Tempo de Criança",
      ano_escolar: "5º Ano",
      telefone: "7191841308",
      endereco: {
        rua: "Rua hilton Rodrigues",
        numero: "158",
        bairro: "Pituba",
        cidade: "Salvador",
        estado: "Bahia",
        cep: "41830630",
        complemento: "apt 702 edf portal do bosque",
        referencia: "Próximo ao hiper ideal",
      },
      password: "$2a$12$8mEzsG7hKhYKuNgs0RW4fOK6AQREgPRkCEJtQmD5t.8nLGfPF6k0S",
      ficha: "Ficha Exemplo",
      modalidade: {
        presencial: true,
        online: false,
      },
      qtd_aulas: 8,
      data_inicio: new Date(),
      responsavelId: responsavelMap[""],
      ativo: true,
    },
    {
      nome: "Ana Valentina Guedes Barbosa",
      email: "adv.marinalvaguedes@hotmail.com",
      escola: "Gurilandia",
      ano_escolar: "4º Ano",
      telefone: "71999255964",
      endereco: {
        rua: "Rua Rio de São Pedro",
        numero: "16",
        bairro: "Graça",
        cidade: "Salvador",
        estado: "Bahia",
        cep: "40150350",
        complemento: "Ed. Mansão Rio de São Pedro",
        referencia: "Próximo à clínica oftalmológica Leitão  Guerra",
      },
      password: "$2a$12$8mEzsG7hKhYKuNgs0RW4fOK6AQREgPRkCEJtQmD5t.8nLGfPF6k0S",
      ficha: "Ficha Exemplo",
      modalidade: {
        presencial: true,
        online: false,
      },
      qtd_aulas: 8,
      data_inicio: new Date(),
      responsavelId: responsavelMap["adv.marinalvaguedes@hotmail.com"],
      ativo: true,
    },
    {
      nome: "Antônio Carlos Cheade Lins Leal Melão",
      email: "",
      escola: "Portinari",
      ano_escolar: "9º Ano",
      telefone: "71999665277",
      endereco: {
        rua: "Rua Hilton Rodrigues",
        numero: "71",
        bairro: "Pituba",
        cidade: "Salvador",
        estado: "Bahia",
        cep: "41830630",
        complemento: "aptº 1103 Edf. Torremolinos",
        referencia: "Final da rua Ceará, após o Hiper Ideal",
      },
      password: "$2a$12$8mEzsG7hKhYKuNgs0RW4fOK6AQREgPRkCEJtQmD5t.8nLGfPF6k0S",
      ficha: "Ficha Exemplo",
      modalidade: {
        presencial: true,
        online: false,
      },
      qtd_aulas: 12,
      data_inicio: new Date(),
      responsavelId: responsavelMap[""],
      ativo: true,
    },
    {
      nome: "Antônio Costa de Oliveira",
      email: "",
      escola: "Sartre Nobel",
      ano_escolar: "7º Ano",
      telefone: "71996527437",
      endereco: {
        rua: "Rua Maranhão",
        numero: "373",
        bairro: "Pituba",
        cidade: "Salvador",
        estado: "Bahia",
        cep: "41830260",
        complemento: "Edf Mansão Vela Branca, apto 901",
        referencia: "Próximo Hotel Manhatan ",
      },
      password: "$2a$12$8mEzsG7hKhYKuNgs0RW4fOK6AQREgPRkCEJtQmD5t.8nLGfPF6k0S",
      ficha: "Ficha Exemplo",
      modalidade: {
        presencial: true,
        online: false,
      },
      qtd_aulas: 4,
      data_inicio: new Date(),
      responsavelId: responsavelMap[""],
=======
      responsavelId: responsavelMap["laissoniarezende@vuyu.es"],
>>>>>>> 2faddd0c6426d1e13ee4f3257978b897bb487c60
      ativo: true,
      financeiro: {
        qtd_aulas: 4,
        valor: "245",
        dta_vencimento: "10/12",
      },
    },
  ];

  // Crie alunos
  const alunos = await prisma.aluno.createMany({
    data: alunosData,
    skipDuplicates: true,
  });

  console.log("Alunos Criados: " + alunos);
}
